### ISSUE TITLE
Suggested enhancement: Associate filter on map fields

### ISSUE THREAD

**Issue by IlkoMichler** [cscan/vue-excel-editor#73]
As far as I found out, that on a map field, i.e.
`<vue-excel-column field="gender" label="Gender" type="map" width="50px" :options="{M:'Male','F':'Female','U':'Unknown'}" />`
on filtering the column key value is used ('M','F','U') and not the fulltext value. It would be very helpful, if in building the filter selection the :to-text- and on submitting the filter the :to-value-Conversion would be accepted. As far as I understand :to-text and :to-value are obsolete for map attributes because the values would be given in the appropiate format beforehand.

**Comment by cscan** [comment]
The options prop support async function, you may try this to return the map dynamically. Hope this help.

**Comment by IlkoMichler** [comment]
Thank you for answering!
You might have found out that I am pretty new in the area. And your solution is so helpful! Thank you!

I might have expressed my issue wrongly:

I have the following table:

`      <b-card>`
`        <vue-excel-editor
            ref="grid"
            v-model="items"
            remember
            filter-row
            no-header-edit
            @update="onUpdateEx"
            @select="onSelect"
        >`
`          <vue-excel-column field="UUID" label="UUID" invisible key-field/>`
`          <vue-excel-column field="MARA_STATS" label="Status" width="120px" type="map" :options="myMARASTATSlist"/>`
`          <vue-excel-column field="MARA_TCODE" label="[MARA-TCODE] Transaktion" width="120px"/>`
...
`        </vue-excel-editor>`
`      </b-card>`
...
`data: () => ({`
`    status_dict: {
      11: 'In Bearbeitung', 12: 'Prüfen', 13: 'Bearbeitet','
    },`
...
`  methods: {`
...
`    myMARASTATSlist() {
      return this.status_dict
    },
`

I have difficulties now to get a valid filter for the Status column. The filter display, that I receive in clicking the "..." in the column filter section, gives a selection list on existing values - it but takes the keys of the status_dict (say "11", "12" aso.) and not the fülltext-status from the status_dict (say "In Bearbeitung" aso.). I want the user to have the latter choices displayed.

This is the reason, why I came up with the idea, to have a use of :to-text and :to-value associated with the map type.

May be there is a way simpler solution to my image of solution. The async funtion for the option prop does not really help me yet.
Thanks for considering in advance.

**Comment by cscan** [comment]
I got it. Yes, I agree that it makes everyone happier if the filtering list shows the list of hash values intead of keys. Let me think about it. This moment I can see a performance issue may need to be addressed during filtering. It is a trade-off between featues and speed. But I am sure I will go back to this later.

**Comment by IlkoMichler** [comment]
Thanks!
Seeing forward to hear a decision and hint. I will keep on finding a Solution with VueJS or similar :-D

**Comment by IlkoMichler** [comment]
I do not understand enough for beeing sure I found a solution that is not at all endangering performance, since it is small.
Isn't it as simple as this?

In your code for `panelFilter.vue` in the  **panel-list-item**-loop just the item description listing must be modified, since (my guess) the default function for the parents to-text v-bind is identity. Then 
`        <div>`
`          <div ref="panelList" class="panel-list">`
`            <div v-for="(item, k) in filteredSortedUniqueValueList.slice(0, nFilterCount)" :key="k"`
`                 class="panel-list-item"`
`                 @click.prevent="filterPanelSelect(item)">`
`              <input type="checkbox" class="panel-checkbox" />`
`<1-- moustached item changed to result value of to-text evaluation -->`
`              <span>{{ to-text(item) }}</span>`
`<1-- end of change -->`
`            </div>`
`          </div>`
`          <div v-if="filteredSortedUniqueValueList.length>500" class="normal-text" style="float:right">`
`            <span v-html="localizedLabel.listFirstNValuesOnly(nFilterCount)" />`
`          </div>`
`        </div>`

The filter value stays to be the items value `filterPanelSelect(item),` the displayed text but is converted, if a to-text-Function is given.

**Comment by cscan** [comment]
to_text is only for displaying, it does not apply in filter process. The filter routine only looks at the value but not text. If convert to text in it, I am afraid there is a performance issue.

**Comment by IlkoMichler** [comment]
I appreciate very much, what you do for the community, cscan! 
Thank you for reopening and considering the task an enhancement. Just for motivation:

I understand, that the v-bind to-text is only used for text display. The existence of a :to-text but indicates, that the field value and the display text differ. On filtering it is straight forward to expect the displayed text, not the hidden value. That is why I suggest this  processing.

Does the filter routine not access the columns features (like type)? If it would it also could check the existence of the v-bind and use it on the most reduced value set possible, means after having collected all the existing values to be listed up to the given count limit.
I still do not fully understand the performance issue. You know better than me. I have not yet found a full solution I can test on ;-).

**Comment by cscan** [comment]
Yes, now the filter routine is quite stright forward due to performance consideration. It just loops the value in v-model array and set the filter flag. I experience it significantly drop down the performance if it tries to call to_text for every value. See any other way to make it faster.

**Comment by sergeyayz** [comment]
First of all thank you for providing this library! It has proven itself useful in our project, but we also ran into the same issue by not being able to filter by values, I understand that there are performance issues with using to_text, but is there a way to use it anyway? Since other options will probably have performance issues as well, or are there other ways to solve this? At any rate, I think this enhancement would be very appreciated since it isn’t trivial to filter by something that isn’t seen inside the excel table.

**Comment by cscan** [comment]
The alternative way is maintaining another string value and use "select" instead of "map", and provide a :change callback to set the value, something like this:

```html
<vue-excel-column field="gender" label="Gender" type="select" width="100px" :options="['Male', 'Female', 'Unknown']" :change="onChangeGender" />
```

```js
onChangeGender(value, oldValue, row) {
    switch(value) {
        case 'Male':
            row.genderID = 1
            break
        case 'Female':
            row.genderID = 2
            break
        case 'Unknown':
            row.genderID = 3
            break
    }
}

```

Hope this help

**Comment by sergeyayz** [comment]
Thank you for a quick response! I will consider this solution.

**Comment by cscan** [comment]
Fixed, see 1.4.2

**Comment by sergeyayz** [comment]
Hello thank you for updating this but when I tried installing 1.4.2. I still see only ids in filter, I am using a map like this one: :options="{M:'Male','F':'Female','U':'Unknown'} but when clicking on filers I only see M, F.... not Male, Female.. is there something I need to do to turn the new updated function on?
